### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by kfieldday** [sc0ttr0berts0n/qwerty-clash-website#1]
- Update leaderboard code with 3 tie rule

These were split to issues #9 and #10
- add ability to click into each player to see stats.
- get rid of "bottom 10" and "top 10" on the leaderboard screen

**Comment by sc0ttr0berts0n** [comment]
Split off click into each player as sep issue #9

**Comment by sc0ttr0berts0n** [comment]
Decided to split off top and bott as well. #10

**Comment by sc0ttr0berts0n** [comment]
donezo
