### ISSUE TITLE
Qwertycast link

### ISSUE THREAD

**Issue by kfieldday** [sc0ttr0berts0n/qwerty-clash-website#6]
Link at bottom to qwertycast.com does not redirect

**Comment by kfieldday** [comment]
this might be an easy one. it's something we found to be an issue on our site's end.  
apparently a link to [qwertycast.com](url) doesn't work
but a link to [www.qwertycast.com](url) does.

**Comment by sc0ttr0berts0n** [comment]
I'm skiping the middle man and linking straight to the link tree. This is implemented and will show up in the next pull request

**Comment by sc0ttr0berts0n** [comment]
@kfieldday Addressed in #15

**Comment by sc0ttr0berts0n** [comment]
donezo
